/* Actions */
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_USERS = 'REQUEST_USERS';

export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS_ERROR = 'RECEIVE_CONVERSATIONS_ERROR';

export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const RECEIVE_CONTACTS = 'RECEIVE_CONTACTS';
export const RECEIVE_CONTACTS_ERROR = 'RECEIVE_CONTACTS_ERROR';


export const REQUEST_CONVERSATION = 'REQUEST_CONVERSATION';
export const RECEIVE_CONVERSATION = 'RECEIVE_CONVERSATION';
export const RECEIVE_CONVERSATION_ERROR = 'RECEIVE_CONVERSATION_ERROR';

export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
export const RECEIVE_MESSAGES_ERROR = 'RECEIVE_MESSAGES_ERROR';


export const POST_MESSAGE = 'POST_MESSAGE';

export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';

export const SET_ACTIVE_VIEW = 'SET_ACTIVE_VIEW';
export const SET_USER = 'SET_USER';