/* Actions */

export const SET_ACTIVE_VIEW = 'SET_ACTIVE_VIEW';

export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_CONVERSATIONS = 'REQUEST_CONVERSATIONS';
export const RECEIVE_CONVERSATIONS = 'RECEIVE_CONVERSATIONS';

export const SHOW_CONVERSATION_VIEW = 'SHOW_CONVERSATION_VIEW';
export const HIDE_CONVERSATION_VIEW = 'HIDE_CONVERSATION_VIEW';